# Generated by Django 3.0.8 on 2020-11-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousels',
            new_name='Carousel',
        ),
    ]
