# Generated by Django 3.0.8 on 2020-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
