# Generated by Django 3.0.8 on 2020-12-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0004_auto_20201209_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
