# Generated by Django 3.0.8 on 2020-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0005_auto_20201209_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('pax', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, default='product_placeholder.png', null=True, upload_to='product_images')),
                ('category', models.ManyToManyField(blank=True, to='foodstore.Category')),
            ],
        ),
    ]
