# Generated by Django 3.0.8 on 2020-12-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0007_auto_20201210_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['group']},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='foodstore.Category'),
        ),
    ]
