# Generated by Django 3.0.8 on 2020-12-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0008_auto_20201210_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['group'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
