# Generated by Django 3.0.8 on 2020-12-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0011_auto_20201218_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='postalCode',
            field=models.IntegerField(),
        ),
    ]
