# Generated by Django 3.0.8 on 2020-12-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0014_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
