# Generated by Django 3.0.8 on 2020-12-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0017_auto_20201226_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
    ]
