# Generated by Django 3.0.8 on 2020-12-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0018_remove_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='used_vouchers',
            field=models.ManyToManyField(blank=True, to='foodstore.Voucher'),
        ),
    ]
