# Generated by Django 3.0.8 on 2020-12-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0020_remove_voucher_maximum_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
