# Generated by Django 3.0.8 on 2020-12-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodstore', '0022_auto_20201228_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount_unit',
            field=models.CharField(choices=[('Amount Off', 'Amount Off'), ('Percent Off', 'Percent Off')], default='Amount Off', max_length=15),
        ),
    ]
